server:
  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
    - type: http
      port: 8081

database:
  user: root
  #password: password
  url: jdbc:mariadb://localhost:3306/ai_observability_bot